site_name: {{ cookiecutter.repository_name }} Documentation
theme: 'material'
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - wikilinks
  - codehilite:
      linenums: True
extra:
  palette:
    primary: '#087da1'
    accent: '#00a889'
  font:
    text: 'Source Sans Pro'

repo_name: '{{ cookiecutter.repository_owner }}/{{ cookiecutter.repository_name }}'
repo_url: 'https://github.com/{{ cookiecutter.repository_owner }}/{{ cookiecutter.repository_name }}'

google_analytics:
  - ''
  - 'auto'
